package View;

import DAO.ConnectDAO;
import Model.Clientes;
import java.util.ArrayList;
import Model.Validador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class JFClientes extends javax.swing.JFrame {

    private javax.swing.JTable jTableClientes;
    private javax.swing.JScrollPane jScrollPane1;

    String operacaoGeral;

    /**
     * Creates new form JFClientes
     */
    public JFClientes() {
        initComponents();
    }

    public JFClientes(String operacao) {
        initComponents();
        operacaoGeral = operacao;

        // Controlar os dados que serão tratados na janela
        if (operacao == "inclusao") {
            jLid_cli.setVisible(true);
            jTFCodCliente.setVisible(true);
            jLnome_cli.setVisible(true);
            jTFNomeCliente.setVisible(true);
            jLende_cli.setVisible(true);
            jTFende_cli.setVisible(true);
            jLnume_cli.setVisible(true);
            jTFnume_cli.setVisible(true);
            jLcompl_cli.setVisible(true);
            jTFCompl_cli.setVisible(true);
            jLbair_cli.setVisible(true);
            jTFbair_cli.setVisible(true);
            jLcida_cli.setVisible(true);
            jTFcida_cli.setVisible(true);
            jLuf_cli.setVisible(true);
            jTFuf_cli.setVisible(true);
            jLcep_cli.setVisible(true);
            jTFcep_cli.setVisible(true);
            jLfone_cli.setVisible(true);
            jTFfone_cli.setVisible(true);
            jLcfp_cli.setVisible(true);
            jTFcpf_cli.setVisible(true);
            jLdata_nasc.setVisible(true);
            jTFdata_nasc.setVisible(true);
            jLcnpj_cli.setVisible(true);
            jTFcnpj_cli.setVisible(true);
            jBConfirmar.setText("Incluir");
            jBConfirmar.setVisible(true);

        }

        if ((operacao == "Alteração")
                || (operacao == "Excluir")
                || (operacao == "Consulta")) {
            jLid_cli.setVisible(true);
            jTFCodCliente.setVisible(true);
            jLnome_cli.setVisible(false);
            jTFNomeCliente.setVisible(false);
            jLende_cli.setVisible(false);
            jTFende_cli.setVisible(false);
            jLnume_cli.setVisible(false);
            jTFnume_cli.setVisible(false);
            jLcompl_cli.setVisible(false);
            jTFCompl_cli.setVisible(false);
            jLbair_cli.setVisible(false);
            jTFbair_cli.setVisible(false);
            jLcida_cli.setVisible(false);
            jTFcida_cli.setVisible(false);
            jLuf_cli.setVisible(false);
            jTFuf_cli.setVisible(false);
            jLcep_cli.setVisible(false);
            jTFcep_cli.setVisible(false);
            jLfone_cli.setVisible(false);
            jTFfone_cli.setVisible(false);
            jLcfp_cli.setVisible(false);
            jTFcpf_cli.setVisible(false);
            jLdata_nasc.setVisible(false);
            jTFdata_nasc.setVisible(false);
            jLcnpj_cli.setVisible(false);
            jTFcnpj_cli.setVisible(false);
            jBConfirmar.setText("Pesquisar");
            jBConfirmar.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLid_cli = new javax.swing.JLabel();
        jLnome_cli = new javax.swing.JLabel();
        jLende_cli = new javax.swing.JLabel();
        jLnume_cli = new javax.swing.JLabel();
        jLuf_cli = new javax.swing.JLabel();
        jLcompl_cli = new javax.swing.JLabel();
        jLcida_cli = new javax.swing.JLabel();
        jLbair_cli = new javax.swing.JLabel();
        jLcep_cli = new javax.swing.JLabel();
        jLfone_cli = new javax.swing.JLabel();
        jLcfp_cli = new javax.swing.JLabel();
        jLdata_nasc = new javax.swing.JLabel();
        jLcnpj_cli = new javax.swing.JLabel();
        jTFCodCliente = new javax.swing.JTextField();
        jTFNomeCliente = new javax.swing.JTextField();
        jTFende_cli = new javax.swing.JTextField();
        jTFnume_cli = new javax.swing.JTextField();
        jTFCompl_cli = new javax.swing.JTextField();
        jTFbair_cli = new javax.swing.JTextField();
        jTFcida_cli = new javax.swing.JTextField();
        jTFuf_cli = new javax.swing.JTextField();
        jTFcep_cli = new javax.swing.JTextField();
        jTFfone_cli = new javax.swing.JTextField();
        jTFcpf_cli = new javax.swing.JTextField();
        jTFdata_nasc = new javax.swing.JTextField();
        jTFcnpj_cli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBConfirmar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLid_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLid_cli.setText("Código do Cliente:");

        jLnome_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLnome_cli.setText("Nome do Cliente:");

        jLende_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLende_cli.setText("Endereço do Cliente:");

        jLnume_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLnume_cli.setText("Número:");

        jLuf_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLuf_cli.setText("UF:");

        jLcompl_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLcompl_cli.setText("Complemento:");

        jLcida_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLcida_cli.setText("Cidade:");

        jLbair_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLbair_cli.setText("Bairro:");

        jLcep_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLcep_cli.setText("CEP:");

        jLfone_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLfone_cli.setText("Telefone:");

        jLcfp_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLcfp_cli.setText("CPF:");

        jLdata_nasc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLdata_nasc.setText("Data de nascimento:");

        jLcnpj_cli.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLcnpj_cli.setText("CNPJ:");

        jTFCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodClienteActionPerformed(evt);
            }
        });

        jTFcep_cli.setToolTipText("er");
        jTFcep_cli.setName(""); // NOI18N

        jLabel1.setText("CADASTRO DE CLIENTES");

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnome_cli)
                            .addComponent(jLid_cli)
                            .addComponent(jLnume_cli)
                            .addComponent(jLcompl_cli)
                            .addComponent(jLbair_cli)
                            .addComponent(jLcida_cli))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFende_cli)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 44, Short.MAX_VALUE)))
                                .addGap(120, 120, 120))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFcida_cli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(jTFCompl_cli, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFbair_cli, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jTFnume_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLende_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLcep_cli)
                                    .addComponent(jLfone_cli)
                                    .addComponent(jLcfp_cli)
                                    .addComponent(jLdata_nasc)
                                    .addComponent(jLcnpj_cli))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFdata_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcpf_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFfone_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcep_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcnpj_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLuf_cli)
                                .addGap(113, 113, 113)
                                .addComponent(jTFuf_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLid_cli)
                            .addComponent(jTFCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLnome_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLende_cli)
                            .addComponent(jTFende_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLnume_cli)
                            .addComponent(jTFnume_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLcompl_cli)
                            .addComponent(jTFCompl_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbair_cli)
                            .addComponent(jTFbair_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLcida_cli)
                            .addComponent(jTFcida_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLuf_cli))
                    .addComponent(jTFuf_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcep_cli)
                    .addComponent(jTFcep_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLfone_cli)
                    .addComponent(jTFfone_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcfp_cli)
                    .addComponent(jTFcpf_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdata_nasc)
                    .addComponent(jTFdata_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcnpj_cli)
                    .addComponent(jTFcnpj_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                          

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.dispose();
    }                                        

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String operacao = operacaoGeral;
        
        if ("inclusao".equals(operacao)) {
            // =========================================================
            // INÍCIO DAS VALIDAÇÕES (INCLUSÃO)
            // =========================================================
            if (!Validador.isCodigoClienteValido(jTFCodCliente.getText())) {
                JOptionPane.showMessageDialog(null, "Código do cliente inválido! Digite um número inteiro maior que zero.");
                jTFCodCliente.requestFocus();
                return; // Aborta
            }
            
            if (!Validador.isCpfValido(jTFcpf_cli.getText())) {
                JOptionPane.showMessageDialog(null, "CPF inválido! Verifique a digitação.");
                jTFcpf_cli.requestFocus();
                return; // Aborta
            }
            // =========================================================
            // FIM DAS VALIDAÇÕES
            // =========================================================

            if (jTFuf_cli.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Estado não informado!");
                jTFuf_cli.requestFocus();
                return;
            }
            
            Clientes dadosClientes = new Clientes(
                    Integer.parseInt(jTFCodCliente.getText()),
                    jTFNomeCliente.getText(),
                    jTFende_cli.getText(),
                    jTFnume_cli.getText(),
                    jTFCompl_cli.getText(),
                    jTFbair_cli.getText(),
                    jTFcida_cli.getText(),
                    jTFuf_cli.getText(),
                    jTFcep_cli.getText(),
                    jTFfone_cli.getText(),
                    jTFcpf_cli.getText(),
                    jTFdata_nasc.getText(),
                    jTFcnpj_cli.getText()
            );

            String dadosSQL = dadosClientes.dadosSQLValues();
            ConnectDAO executarSQL = new ConnectDAO();
            executarSQL.insereRegistroJFDB("clientes", dadosSQL);

            this.dispose();
        }

        if ("ConsultaGeral".equals(operacao)) {
            Clientes cliente_tela = new Clientes();

            ConnectDAO objcon = new ConnectDAO();
            cliente_tela = objcon.pesquiseClienteJFDB("CLIENTES", "id_cli = '" + jTFCodCliente.getText() + "'");
            //Os campos abaixo são do botão ler
            jTFNomeCliente.setText(cliente_tela.getNome_cli());
            jTFende_cli.setText(cliente_tela.getEnde_cli());
            jTFnume_cli.setText(cliente_tela.getNume_cli());
            jTFCompl_cli.setText(cliente_tela.getComlp_cli());
            jTFbair_cli.setText(cliente_tela.getBair_cli());
            jTFcida_cli.setText(cliente_tela.getCida_cli());
            jTFuf_cli.setText(cliente_tela.getUf_cli());
            jTFcep_cli.setText(cliente_tela.getCep_cli());
            jTFfone_cli.setText(cliente_tela.getFone_cli());
            jTFcpf_cli.setText(cliente_tela.getCpf_cli());
            jTFdata_nasc.setText(cliente_tela.getData_nasc());
            jTFcnpj_cli.setText(cliente_tela.getCnpj_cli());

            jLid_cli.setVisible(true);
            jTFCodCliente.setVisible(true);
            jLnome_cli.setVisible(true);
            jTFNomeCliente.setVisible(true);
            jLende_cli.setVisible(true);
            jTFende_cli.setVisible(true);
            jLnume_cli.setVisible(true);
            jTFnume_cli.setVisible(true);
            jLcompl_cli.setVisible(true);
            jTFCompl_cli.setVisible(true);
            jLbair_cli.setVisible(true);
            jTFbair_cli.setVisible(true);
            jLcida_cli.setVisible(true);
            jTFcida_cli.setVisible(true);
            jLuf_cli.setVisible(true);
            jTFuf_cli.setVisible(true);
            jLcep_cli.setVisible(true);
            jTFcep_cli.setVisible(true);
            jLfone_cli.setVisible(true);
            jTFfone_cli.setVisible(true);
            jLcfp_cli.setVisible(true);
            jTFcpf_cli.setVisible(true);
            jLdata_nasc.setVisible(true);
            jTFdata_nasc.setVisible(true);
            jLcnpj_cli.setVisible(true);
            jTFcnpj_cli.setVisible(true);

            jTFCodCliente.setEditable(false);
            jTFNomeCliente.setEditable(false);
            jTFende_cli.setEditable(false);
            jTFnume_cli.setEditable(false);
            jTFCompl_cli.setEditable(false);
            jTFbair_cli.setEditable(false);
            jTFcida_cli.setEditable(false);
            jTFuf_cli.setEditable(false);
            jTFcep_cli.setEditable(false);
            jTFfone_cli.setEditable(false);
            jTFcpf_cli.setEditable(false);
            jTFdata_nasc.setEditable(false);
            jTFcnpj_cli.setEditable(false);
        }

        if (operacao.equals("ConsultaGeral")) {
            String op = "ConsultaGeral";
            JFConsultaClientes telaConsulta = new JFConsultaClientes(op);
            telaConsulta.setVisible(true);
        }

        if (operacao == "Exclusão") {
            int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja Excluir o Registro?",
                    "Confirmar Exclusão",
                    JOptionPane.YES_NO_OPTION
            );
            if (resposta == JOptionPane.YES_OPTION) {
                ConnectDAO objcon = new ConnectDAO();
                objcon.excluiRegistroJFDB("CLIENTES", "id_cli = '"
                        + jTFCodCliente.getText() + "'");
            }
            this.dispose();
        }

        if (operacao == "Excluir") {
            Clientes cliente_tela = new Clientes();

            ConnectDAO objcon = new ConnectDAO();
            cliente_tela = objcon.pesquiseClienteJFDB("CLIENTES", "id_cli = '" + jTFCodCliente.getText() + "'");
            //Os campos abaixo são do botão ler
            jTFNomeCliente.setText(cliente_tela.getNome_cli());
            jTFende_cli.setText(cliente_tela.getEnde_cli());
            jTFnume_cli.setText(cliente_tela.getNume_cli());
            jTFCompl_cli.setText(cliente_tela.getComlp_cli());
            jTFbair_cli.setText(cliente_tela.getBair_cli());
            jTFcida_cli.setText(cliente_tela.getCida_cli());
            jTFuf_cli.setText(cliente_tela.getUf_cli());
            jTFcep_cli.setText(cliente_tela.getCep_cli());
            jTFfone_cli.setText(cliente_tela.getFone_cli());
            jTFcpf_cli.setText(cliente_tela.getCpf_cli());
            jTFdata_nasc.setText(cliente_tela.getData_nasc());
            jTFcnpj_cli.setText(cliente_tela.getCnpj_cli());

            jLid_cli.setVisible(true);
            jTFCodCliente.setVisible(true);
            jLnome_cli.setVisible(true);
            jTFNomeCliente.setVisible(true);
            jLende_cli.setVisible(true);
            jTFende_cli.setVisible(true);
            jLnume_cli.setVisible(true);
            jTFnume_cli.setVisible(true);
            jLcompl_cli.setVisible(true);
            jTFCompl_cli.setVisible(true);
            jLbair_cli.setVisible(true);
            jTFbair_cli.setVisible(true);
            jLcida_cli.setVisible(true);
            jTFcida_cli.setVisible(true);
            jLuf_cli.setVisible(true);
            jTFuf_cli.setVisible(true);
            jLcep_cli.setVisible(true);
            jTFcep_cli.setVisible(true);
            jLfone_cli.setVisible(true);
            jTFfone_cli.setVisible(true);
            jLcfp_cli.setVisible(true);
            jTFcpf_cli.setVisible(true);
            jLdata_nasc.setVisible(true);
            jTFdata_nasc.setVisible(true);
            jLcnpj_cli.setVisible(true);
            jTFcnpj_cli.setVisible(true);

            jTFCodCliente.setEditable(false);
            jTFNomeCliente.setEditable(false);
            jTFende_cli.setEditable(false);
            jTFnume_cli.setEditable(false);
            jTFCompl_cli.setEditable(false);
            jTFbair_cli.setEditable(false);
            jTFcida_cli.setEditable(false);
            jTFuf_cli.setEditable(false);
            jTFcep_cli.setEditable(false);
            jTFfone_cli.setEditable(false);
            jTFcpf_cli.setEditable(false);
            jTFdata_nasc.setEditable(false);
            jTFcnpj_cli.setEditable(false);
            jBConfirmar.setText("Excluir");
            jBConfirmar.setVisible(true);
            operacaoGeral = "Exclusão";
        }
        
        if (operacao == "Alteração") {
            Clientes cliente_tela = new Clientes();
            ConnectDAO objcon = new ConnectDAO();
            cliente_tela = objcon.pesquiseClienteJFDB("CLIENTES", "id_cli = '" + jTFCodCliente.getText() + "'");
            // OS CAMPOS ABAIXO SÃO DO BOTÃO LER
            jTFNomeCliente.setText(cliente_tela.getNome_cli());
            jTFende_cli.setText(cliente_tela.getEnde_cli());
            jTFnume_cli.setText(cliente_tela.getNume_cli());
            jTFCompl_cli.setText(cliente_tela.getComlp_cli());
            jTFbair_cli.setText(cliente_tela.getBair_cli());
            jTFcida_cli.setText(cliente_tela.getCida_cli());
            jTFuf_cli.setText(cliente_tela.getUf_cli());
            jTFcep_cli.setText(cliente_tela.getCep_cli());
            jTFfone_cli.setText(cliente_tela.getFone_cli());
            jTFcpf_cli.setText(cliente_tela.getCpf_cli());
            jTFdata_nasc.setText(cliente_tela.getData_nasc());
            jTFcnpj_cli.setText(cliente_tela.getCnpj_cli());

            /*
            * aqui vamos liberar os campos da tela para serem visualizados
            * pelo usuário
             */
            jTFCodCliente.setVisible(true);
            jLnome_cli.setVisible(true);
            jTFNomeCliente.setVisible(true);
            jLende_cli.setVisible(true);
            jTFende_cli.setVisible(true);
            jLnume_cli.setVisible(true);
            jTFnume_cli.setVisible(true);
            jLcompl_cli.setVisible(true);
            jTFCompl_cli.setVisible(true);
            jLbair_cli.setVisible(true);
            jTFbair_cli.setVisible(true);
            jLcida_cli.setVisible(true);
            jTFcida_cli.setVisible(true);
            jLuf_cli.setVisible(true);
            jTFuf_cli.setVisible(true);
            jLcep_cli.setVisible(true);
            jTFcep_cli.setVisible(true);
            jLfone_cli.setVisible(true);
            jTFfone_cli.setVisible(true);
            jLcfp_cli.setVisible(true);
            jTFcpf_cli.setVisible(true);
            jLdata_nasc.setVisible(true);
            jTFdata_nasc.setVisible(true);
            jLcnpj_cli.setVisible(true);
            jTFcnpj_cli.setVisible(true);
            jBConfirmar.setText("Alterar");
            jBConfirmar.setVisible(true);
            operacaoGeral = "Alterar";
        }
        
        if ("Alterar".equals(operacao)) {
            // =========================================================
            // INÍCIO DAS VALIDAÇÕES (ALTERAÇÃO)
            // =========================================================
            if (!Validador.isCodigoClienteValido(jTFCodCliente.getText())) {
                JOptionPane.showMessageDialog(null, "Código do cliente inválido! Digite um número inteiro maior que zero.");
                jTFCodCliente.requestFocus();
                return; // Aborta
            }
            
            if (!Validador.isCpfValido(jTFcpf_cli.getText())) {
                JOptionPane.showMessageDialog(null, "CPF inválido! Verifique a digitação.");
                jTFcpf_cli.requestFocus();
                return; // Aborta
            }
            // =========================================================
            // FIM DAS VALIDAÇÕES
            // =========================================================

            Clientes dadosClientes = new Clientes(
                    Integer.parseInt(jTFCodCliente.getText()),
                    jTFNomeCliente.getText(),
                    jTFende_cli.getText(),
                    jTFnume_cli.getText(),
                    jTFCompl_cli.getText(),
                    jTFbair_cli.getText(),
                    jTFcida_cli.getText(),
                    jTFuf_cli.getText(),
                    jTFcep_cli.getText(),
                    jTFfone_cli.getText(),
                    jTFcpf_cli.getText(),
                    jTFdata_nasc.getText(),
                    jTFcnpj_cli.getText()
            );
            /* Na sequência, manda executar a função para inserir os registros no banco
             de dados selecionado  */
            ConnectDAO objcon = new ConnectDAO();
            String dadosSQL = dadosClientes.alteraDadosSQLValues();
            objcon.alteraRegistroJFDB("CLIENTES", dadosSQL,
                    "ID_CLI=" + jTFCodCliente.getText());

            this.dispose();
        }
    }                                           

    private void jTFCodClienteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFClientes("inclusao").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbair_cli;
    private javax.swing.JLabel jLcep_cli;
    private javax.swing.JLabel jLcfp_cli;
    private javax.swing.JLabel jLcida_cli;
    private javax.swing.JLabel jLcnpj_cli;
    private javax.swing.JLabel jLcompl_cli;
    private javax.swing.JLabel jLdata_nasc;
    private javax.swing.JLabel jLende_cli;
    private javax.swing.JLabel jLfone_cli;
    private javax.swing.JLabel jLid_cli;
    private javax.swing.JLabel jLnome_cli;
    private javax.swing.JLabel jLnume_cli;
    private javax.swing.JLabel jLuf_cli;
    private javax.swing.JTextField jTFCodCliente;
    private javax.swing.JTextField jTFCompl_cli;
    private javax.swing.JTextField jTFNomeCliente;
    private javax.swing.JTextField jTFbair_cli;
    private javax.swing.JTextField jTFcep_cli;
    private javax.swing.JTextField jTFcida_cli;
    private javax.swing.JTextField jTFcnpj_cli;
    private javax.swing.JTextField jTFcpf_cli;
    private javax.swing.JTextField jTFdata_nasc;
    private javax.swing.JTextField jTFende_cli;
    private javax.swing.JTextField jTFfone_cli;
    private javax.swing.JTextField jTFnume_cli;
    private javax.swing.JTextField jTFuf_cli;
    // End of variables declaration                   
}