/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ConnectDAO;
import Model.Produtos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class JFProdutos extends javax.swing.JFrame {

    private javax.swing.JTable jTableProdutos;
    private javax.swing.JScrollPane jScrollPane1;

    String operacaoGeral;

    /**
     * Creates new form JFProdutos
     */
    public JFProdutos() {
        initComponents();
    }

    public JFProdutos(String operacao) {
        initComponents();
        operacaoGeral = operacao;

        // Controlar os dados que serão tratados na janela
        if (operacao.equals("Inclusão")) {
            jLCdProduto.setVisible(true);
            jTFCdProduto.setVisible(true);
            jTFCdProduto.setEditable(false); //Não é necessário digital o código (CdProduto INT PRIMARY KEY IDENTITY)
            jLNome.setVisible(true);
            jTFNome.setVisible(true);
            jLTipo.setVisible(true);
            jTFTipo.setVisible(true);
            jLPreco.setVisible(true);
            jTFPreco.setVisible(true);
            jLQtdTotal.setVisible(true);
            jTFQtdTotal.setVisible(true);
            jLdtCadastro.setVisible(true);
            jTFdtCadastro.setVisible(true);
            jLDtUltimaAtz.setVisible(true);
            jTFDtUltimaAtz.setVisible(true);
            jLStatus.setVisible(true);
            jTFStatus.setVisible(true);

            jBConfirmar.setText("Incluir");
        }

        if (operacao.equals("Alteração")
                || operacao.equals("Excluir")
                || operacao.equals("Consulta")) {

            jLCdProduto.setVisible(true);
            jTFCdProduto.setVisible(true);

            jLNome.setVisible(false);
            jTFNome.setVisible(false);
            jLTipo.setVisible(false);
            jTFTipo.setVisible(false);
            jLPreco.setVisible(false);
            jTFPreco.setVisible(false);
            jLQtdTotal.setVisible(false);
            jTFQtdTotal.setVisible(false);
            jLdtCadastro.setVisible(false);
            jTFdtCadastro.setVisible(false);
            jLDtUltimaAtz.setVisible(false);
            jTFDtUltimaAtz.setVisible(false);
            jLStatus.setVisible(false);
            jTFStatus.setVisible(false);

            jBConfirmar.setText("Pesquisar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLQtdTotal = new javax.swing.JLabel();
        jBConfirmar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jLStatus = new javax.swing.JLabel();
        jTFdtCadastro = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jTFTipo = new javax.swing.JTextField();
        jTFPreco = new javax.swing.JTextField();
        jTFQtdTotal = new javax.swing.JTextField();
        jTFStatus = new javax.swing.JTextField();
        jLdtCadastro = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLPreco = new javax.swing.JLabel();
        jLDtUltimaAtz = new javax.swing.JLabel();
        jTFDtUltimaAtz = new javax.swing.JTextField();
        jLCdProduto = new javax.swing.JLabel();
        jTFCdProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE PRODUTOS");

        jLQtdTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLQtdTotal.setText("Quantidade total:");

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jLStatus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLStatus.setText("Status:");

        jLdtCadastro.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLdtCadastro.setText("Dia do cadastro:");

        jLNome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLNome.setText("Nome do produto:");

        jLTipo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLTipo.setText("Tipo de produto:");

        jLPreco.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLPreco.setText("Preço do produto(xx.xx):");

        jLDtUltimaAtz.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLDtUltimaAtz.setText("Data da Ultima Atz:");

        jTFDtUltimaAtz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDtUltimaAtzActionPerformed(evt);
            }
        });

        jLCdProduto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLCdProduto.setText("Código do produto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome)
                            .addComponent(jLdtCadastro)
                            .addComponent(jLPreco)
                            .addComponent(jLQtdTotal)
                            .addComponent(jLStatus)
                            .addComponent(jLDtUltimaAtz, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFQtdTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFPreco)
                                .addComponent(jTFTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFdtCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFDtUltimaAtz, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCdProduto)
                    .addComponent(jTFCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLdtCadastro)
                        .addGap(8, 8, 8)
                        .addComponent(jLNome)
                        .addGap(16, 16, 16)
                        .addComponent(jLTipo)
                        .addGap(121, 121, 121)
                        .addComponent(jLStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFdtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPreco))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFQtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLQtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDtUltimaAtz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDtUltimaAtz, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:

        String operacao = operacaoGeral;
        if (operacao.equals("Inclusão")) {

            
            Produtos novoProduto = new Produtos(
                    jTFdtCadastro.getText(),
                    jTFNome.getText(),
                    jTFTipo.getText(),
                    Float.parseFloat(jTFPreco.getText()),
                    Integer.parseInt(jTFQtdTotal.getText()),
                    jTFDtUltimaAtz.getText(),
                    jTFStatus.getText()
            );

            ConnectDAO con = new ConnectDAO();

            
            con.insereRegistroJFDB(
                    "PRODUTOS (dtCadastro, Nome, Tipo, Preco, QtdTotal, DtUltimaAtz, Status)",
                    novoProduto.dadosSQLValues()
            );

            this.dispose();
        }

        if (operacao.equals("Consulta")) {

            Produtos prod = new Produtos();
            ConnectDAO con = new ConnectDAO();

            prod = con.pesquiseProdutoJFDB("PRODUTOS",
                    "CdProduto = '" + jTFCdProduto.getText() + "'");

            jTFNome.setText(prod.getNome());
            jTFTipo.setText(prod.getTipo());
            jTFPreco.setText(String.valueOf(prod.getPreco()));
            jTFQtdTotal.setText(String.valueOf(prod.getQtdTotal()));
            jTFdtCadastro.setText(prod.getDtCadastro());
            jTFDtUltimaAtz.setText(prod.getDtUltimaAtz());
            jTFStatus.setText(prod.getStatus());

            // mostra todos
            jLNome.setVisible(true);
            jTFNome.setVisible(true);
            jLTipo.setVisible(true);
            jTFTipo.setVisible(true);
            jLPreco.setVisible(true);
            jTFPreco.setVisible(true);
            jLQtdTotal.setVisible(true);
            jTFQtdTotal.setVisible(true);
            jLdtCadastro.setVisible(true);
            jTFdtCadastro.setVisible(true);
            jLDtUltimaAtz.setVisible(true);
            jTFDtUltimaAtz.setVisible(true);
            jLStatus.setVisible(true);
            jTFStatus.setVisible(true);

            // bloqueia edição
            jTFNome.setEditable(false);
            jTFTipo.setEditable(false);
            jTFPreco.setEditable(false);
            jTFQtdTotal.setEditable(false);
            jTFdtCadastro.setEditable(false);
            jTFDtUltimaAtz.setEditable(false);
            jTFStatus.setEditable(false);
        }

        if (operacao.equals("ConsultaGeral")) {
            String op = "ConsultaGeral";
            JFConsultaClientes telaConsulta = new JFConsultaClientes(op);
            telaConsulta.setVisible(true);
        }

        if (operacao.equals("Exclusão")) {

            int resp = JOptionPane.showConfirmDialog(null,
                    "Excluir o registro?",
                    "Confirmar", JOptionPane.YES_NO_OPTION);

            if (resp == JOptionPane.YES_OPTION) {
                ConnectDAO con = new ConnectDAO();
                con.excluiRegistroJFDB("PRODUTOS",
                        "CdProduto = '" + jTFCdProduto.getText() + "'");
            }

            this.dispose();
        }

        if (operacao.equals("Excluir")) {

            Produtos prod_tela = new Produtos();

            ConnectDAO objcon = new ConnectDAO();
            prod_tela = objcon.pesquiseProdutoJFDB(
                    "PRODUTOS",
                    "CdProduto = '" + jTFCdProduto.getText() + "'"
            );

            // Preenche os campos com os dados buscados
            jTFdtCadastro.setText(prod_tela.getDtCadastro());
            jTFNome.setText(prod_tela.getNome());
            jTFTipo.setText(prod_tela.getTipo());
            jTFPreco.setText(String.valueOf(prod_tela.getPreco()));
            jTFQtdTotal.setText(String.valueOf(prod_tela.getQtdTotal()));
            jTFDtUltimaAtz.setText(prod_tela.getDtUltimaAtz());
            jTFStatus.setText(prod_tela.getStatus());

            // deixa visíveis
            jLCdProduto.setVisible(true);
            jTFCdProduto.setVisible(true);
            jLNome.setVisible(true);
            jTFNome.setVisible(true);
            jLTipo.setVisible(true);
            jTFTipo.setVisible(true);
            jLPreco.setVisible(true);
            jTFPreco.setVisible(true);
            jLQtdTotal.setVisible(true);
            jTFQtdTotal.setVisible(true);
            jLdtCadastro.setVisible(true);
            jTFdtCadastro.setVisible(true);
            jLDtUltimaAtz.setVisible(true);
            jTFDtUltimaAtz.setVisible(true);
            jLStatus.setVisible(true);
            jTFStatus.setVisible(true);

            // deixa tudo bloqueado para edição
            jTFdtCadastro.setEditable(false);
            jTFNome.setEditable(false);
            jTFTipo.setEditable(false);
            jTFPreco.setEditable(false);
            jTFQtdTotal.setEditable(false);
            jTFDtUltimaAtz.setEditable(false);
            jTFStatus.setEditable(false);
            jTFCdProduto.setEditable(false);

            jBConfirmar.setText("Excluir");
            jBConfirmar.setVisible(true);
            operacaoGeral = "Exclusão";
        }

        if (operacao.equals("Alteração")) {

            Produtos prod_tela = new Produtos();
            ConnectDAO objcon = new ConnectDAO();

            prod_tela = objcon.pesquiseProdutoJFDB(
                    "PRODUTOS",
                    "CdProduto = '" + jTFCdProduto.getText() + "'"
            );

            // Preenche os campos
            jTFdtCadastro.setText(prod_tela.getDtCadastro());
            jTFNome.setText(prod_tela.getNome());
            jTFTipo.setText(prod_tela.getTipo());
            jTFPreco.setText(String.valueOf(prod_tela.getPreco()));
            jTFQtdTotal.setText(String.valueOf(prod_tela.getQtdTotal()));
            jTFDtUltimaAtz.setText(prod_tela.getDtUltimaAtz());
            jTFStatus.setText(prod_tela.getStatus());

            /*
     * Libera os campos para edição
             */
            jTFdtCadastro.setVisible(true);
            jLNome.setVisible(true);
            jTFNome.setVisible(true);
            jLTipo.setVisible(true);
            jTFTipo.setVisible(true);
            jLPreco.setVisible(true);
            jTFPreco.setVisible(true);
            jLQtdTotal.setVisible(true);
            jTFQtdTotal.setVisible(true);
            jLDtUltimaAtz.setVisible(true);
            jTFDtUltimaAtz.setVisible(true);
            jLStatus.setVisible(true);
            jTFStatus.setVisible(true);
            jLCdProduto.setVisible(true);
            jTFCdProduto.setVisible(true);

            jTFCdProduto.setEditable(false); // código não pode ser alterado

            jBConfirmar.setText("Alterar");
            jBConfirmar.setVisible(true);
            operacaoGeral = "Alterar";
        }

        if (operacao.equals("Alterar")) {

            Produtos dadosProdutos = new Produtos(
                    Integer.parseInt(jTFCdProduto.getText()),
                    jTFdtCadastro.getText(),
                    jTFNome.getText(),
                    jTFTipo.getText(),
                    Float.parseFloat(jTFPreco.getText()),
                    Integer.parseInt(jTFQtdTotal.getText()),
                    jTFDtUltimaAtz.getText(),
                    jTFStatus.getText()
            );

            ConnectDAO con = new ConnectDAO();
            con.alteraRegistroJFDB(
                    "PRODUTOS",
                    dadosProdutos.alteraDadosSQLValues(),
                    "CdProduto=" + jTFCdProduto.getText()
            );

            this.dispose();
        }


    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jTFDtUltimaAtzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDtUltimaAtzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDtUltimaAtzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBFechar;
    private javax.swing.JLabel jLCdProduto;
    private javax.swing.JLabel jLDtUltimaAtz;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPreco;
    private javax.swing.JLabel jLQtdTotal;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLdtCadastro;
    private javax.swing.JTextField jTFCdProduto;
    private javax.swing.JTextField jTFDtUltimaAtz;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPreco;
    private javax.swing.JTextField jTFQtdTotal;
    private javax.swing.JTextField jTFStatus;
    private javax.swing.JTextField jTFTipo;
    private javax.swing.JTextField jTFdtCadastro;
    // End of variables declaration//GEN-END:variables
}
