/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Alunos
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static void VisibleTrue() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMcliente = new javax.swing.JMenu();
        jMIClienteInclusao = new javax.swing.JMenuItem();
        jMIClienteAlteracao = new javax.swing.JMenuItem();
        jMIClienteExclusao = new javax.swing.JMenuItem();
        jMIClienteConsulta = new javax.swing.JMenuItem();
        jMIClienteConsultaGeral = new javax.swing.JMenuItem();
        jMIClienteRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIProdutosInclusao = new javax.swing.JMenuItem();
        jMIProdutosAlteracao = new javax.swing.JMenuItem();
        jMIProdutosExclusao = new javax.swing.JMenuItem();
        jMIProdutosConsulta = new javax.swing.JMenuItem();
        jMIProdutosConsultaGeral = new javax.swing.JMenuItem();
        jMIProdutosRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMcliente.setText("Cliente");

        jMIClienteInclusao.setText("Inclusão");
        jMIClienteInclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteInclusaoActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteInclusao);

        jMIClienteAlteracao.setText("Alteração");
        jMIClienteAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteAlteracaoActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteAlteracao);

        jMIClienteExclusao.setText("Exclusão");
        jMIClienteExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteExclusaoActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteExclusao);

        jMIClienteConsulta.setText("Consulta");
        jMIClienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteConsultaActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteConsulta);

        jMIClienteConsultaGeral.setText("ConsultaGeral");
        jMIClienteConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteConsultaGeralActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteConsultaGeral);

        jMIClienteRelatorio.setText("Relatório");
        jMIClienteRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteRelatorioActionPerformed(evt);
            }
        });
        jMcliente.add(jMIClienteRelatorio);

        jMenuBar1.add(jMcliente);

        jMenu2.setText("Produtos");

        jMIProdutosInclusao.setText("Inclusão");
        jMIProdutosInclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosInclusaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosInclusao);

        jMIProdutosAlteracao.setText("Alteração");
        jMIProdutosAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosAlteracaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosAlteracao);

        jMIProdutosExclusao.setText("Exclusão");
        jMIProdutosExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosExclusaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosExclusao);

        jMIProdutosConsulta.setText("Consulta");
        jMIProdutosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosConsulta);

        jMIProdutosConsultaGeral.setText("ConsultaGeral");
        jMIProdutosConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosConsultaGeralActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosConsultaGeral);

        jMIProdutosRelatorio.setText("Relatório");
        jMIProdutosRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdutosRelatorioActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProdutosRelatorio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIClienteInclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteInclusaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Inclusão";
        JFClientes clientes = new JFClientes(operacao);
        clientes.setVisible(true);
    }//GEN-LAST:event_jMIClienteInclusaoActionPerformed

    private void jMIClienteExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteExclusaoActionPerformed
        // TODO d your handling code here:
        String operacao = "Excluir";
        JFClientes clientes = new JFClientes(operacao);
        clientes.setVisible(true);
    }//GEN-LAST:event_jMIClienteExclusaoActionPerformed

    private void jMIClienteAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteAlteracaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Alteração";
        JFClientes clientes = new JFClientes(operacao);
        clientes.setVisible(true);
    }//GEN-LAST:event_jMIClienteAlteracaoActionPerformed

    private void jMIClienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteConsultaActionPerformed
        // TODO add your handling code here:
        String operacao = "Consulta";
        JFClientes clientes = new JFClientes(operacao);
        clientes.setVisible(true);
    }//GEN-LAST:event_jMIClienteConsultaActionPerformed

    private void jMIClienteConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteConsultaGeralActionPerformed
        // TODO add your handling code here:
        String operacao = "ConsultaGeral";
        JFConsultaClientes consulta = new JFConsultaClientes(operacao);
        consulta.setVisible(true);

    }//GEN-LAST:event_jMIClienteConsultaGeralActionPerformed

    private void jMIClienteRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteRelatorioActionPerformed
        // TODO add your handling code here:
        String operacao = "Relatorio";
        JFConsultaClientes consulta = new JFConsultaClientes(operacao);
        consulta.setVisible(true);

    }//GEN-LAST:event_jMIClienteRelatorioActionPerformed

    private void jMIProdutosInclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosInclusaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Inclusão";
        JFProdutos produtos = new JFProdutos(operacao);
        produtos.setVisible(true);
    }//GEN-LAST:event_jMIProdutosInclusaoActionPerformed

    private void jMIProdutosAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosAlteracaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Alteração";
        JFProdutos produtos = new JFProdutos(operacao);
        produtos.setVisible(true);
    }//GEN-LAST:event_jMIProdutosAlteracaoActionPerformed

    private void jMIProdutosExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosExclusaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFProdutos produtos = new JFProdutos(operacao);
        produtos.setVisible(true);
    }//GEN-LAST:event_jMIProdutosExclusaoActionPerformed

    private void jMIProdutosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosConsultaActionPerformed
        // TODO add your handling code here:
        String operacao = "Consulta";
        JFProdutos produtos = new JFProdutos(operacao);
        produtos.setVisible(true);
    }//GEN-LAST:event_jMIProdutosConsultaActionPerformed

    private void jMIProdutosConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosConsultaGeralActionPerformed
        // TODO add your handling code here:
        String operacao = "ConsultaGeral";
        JFConsultaProdutos consulta = new JFConsultaProdutos(operacao);
        consulta.setVisible(true);
    }//GEN-LAST:event_jMIProdutosConsultaGeralActionPerformed

    private void jMIProdutosRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdutosRelatorioActionPerformed
        // TODO add your handling code here:
        String operacao = "Relatório";
        JFConsultaProdutos consulta = new JFConsultaProdutos(operacao);
        consulta.setVisible(true);
    }//GEN-LAST:event_jMIProdutosRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMIClienteAlteracao;
    private javax.swing.JMenuItem jMIClienteConsulta;
    private javax.swing.JMenuItem jMIClienteConsultaGeral;
    private javax.swing.JMenuItem jMIClienteExclusao;
    private javax.swing.JMenuItem jMIClienteInclusao;
    private javax.swing.JMenuItem jMIClienteRelatorio;
    private javax.swing.JMenuItem jMIProdutosAlteracao;
    private javax.swing.JMenuItem jMIProdutosConsulta;
    private javax.swing.JMenuItem jMIProdutosConsultaGeral;
    private javax.swing.JMenuItem jMIProdutosExclusao;
    private javax.swing.JMenuItem jMIProdutosInclusao;
    private javax.swing.JMenuItem jMIProdutosRelatorio;
    private javax.swing.JMenu jMcliente;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
